### PR TITLE
Fix Indentation and Update Compute Function

### PR DESCRIPTION
**Pull request by erickfaria**
Hello,

I have made some updates to the code which should resolve the issues we were experiencing. Here are the details:

1. **Indentation**: I have corrected the indentation in our codebase to ensure it adheres to our style guidelines.

2. **Update to Compute Function**: I have made a significant change to the `compute` function. The original function was as follows:

```python
def compute(self):
    y1 = odeint(self.dCdt, self.C0, t=self.t, rtol=0.01, atol=0.01)
    return pd.DataFrame(y1, columns=self.ks_pulls)
```

In the original function, the odeint function was called without passing the necessary arguments (self.input_carbon, self.farmyard_manure, self.DR). I have updated the function to include these arguments. Here is the updated function:

```python
def compute(self):
    y1 = odeint(self.dCdt, self.C0, t=self.t, args=(self.input_carbon, self.farmyard_manure, self.DR), rtol=0.01, atol=0.01)
    return pd.DataFrame(y1, columns=self.ks_pulls)
```

These changes should eliminate the errors we were encountering. I have tested the updates on my end, and everything is functioning as expected.

Please review these changes and let me know if you have any questions or feedback.

### CODE REVIEW

**Comment by mishagrol** [comment]
@erickfaria I think we should update this function to use np.array for carbon and manure input\

```
def get_input_flux(
        self,
        input_carbon: Union[float, np.ndarray],
        farmyard_manure: Union[float, np.ndarray] = 0,
        DR: Union[float, np.ndarray] = 1.44,
    ) -> np.ndarray:
        """
            Get amount of litter inputs

        Args:
            input_carbon (float): A scalar or np.array
                                the amount of litter inputs by time. Defaults to 1.7.
            farmyard_manure (float, optional): A scalar or np.array object specifying the amount
                                                of Farm Yard Manure inputs by time.
                                                Defaults to 0.
            DR (float, optional): A scalar representing the ratio of decomposable plant material
                                to resistant plant material (DPM/RPM). Defaults to 1.44.

        Returns:
            np.ndarray: input_DPM, input_RPM, input_BIO, input_HUM, input_IOM
        """

        gamma = DR / (1 + DR)
        input_DPM = input_carbon * gamma + (farmyard_manure * 0.49)
        input_DPM = np.sum(input_DPM)
        input_RPM = input_carbon * (1 - gamma) + (farmyard_manure * 0.49)
        input_RPM = np.sum(input_RPM)
        input_BIO = 0
        input_HUM = farmyard_manure * 0.02
        input_RPM = np.sum(input_HUM)
        input_IOM = 0
        return np.array(
            [
                input_DPM,
                input_RPM,
                input_BIO,
                input_HUM,
                input_IOM,
            ]
        )


```

**Comment by erickfaria** [comment]
Hello @mishagrol ok, I will work on it. I just need more time, I'm kind of busy this days.

**Comment by mishagrol** [comment]
@erickfaria 
> Hello @mishagrol ok, I will work on it. I just need more time, I'm kind of busy this days.


Thank you! I have fixed these problems and added some new functions, according to request from   #9

**Comment by erickfaria** [comment]
> @erickfaria
> 
> > Hello @mishagrol ok, I will work on it. I just need more time, I'm kind of busy this days.
> 
> Thank you! I have fixed these problems and added some new functions, according to request from #9

Nice, thank you. I will close this MR

**Pull request closed without merging**
